In [0]:
import pandas as pd
import numpy as np
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.metrics.pairwise import cosine_similarity

In [0]:
###### helper functions. Use them when needed #######
def get_title_from_index(index):
	return df[df.index == index]["title"].values[0]

def get_index_from_title(title):
	return df[df.title == title]["index"].values[0]
##################################################

In [0]:
##Step 1: Read CSV File

url='https://raw.githubusercontent.com/codeheroku/Introduction-to-Machine-Learning/master/Building%20a%20Movie%20Recommendation%20Engine/movie_dataset.csv'


df=pd.read_csv(url)

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4803 entries, 0 to 4802
Data columns (total 24 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   index                 4803 non-null   int64
 1   budget                4803 non-null   int64
 2   genres                4775 non-null   object
 3   homepage              1712 non-null   object
 4   id                    4803 non-null   int64
 5   keywords              4391 non-null   object
 6   original_language     4803 non-null   object
 7   original_title        4803 non-null   object
 8   overview              4800 non-null   object
 9   popularity            4803 non-null   float64
 10  production_companies  4803 non-null   object
 11  production_countries  4803 non-null   object
 12  release_date          4802 non-null   object
 13  revenue               4803 non-null   int64
 14  runtime               4801 non-null   float64
 15  spoken_languages      4803 non-null   object
 16  status                4803 non-null   object
 17  tagline               3959 non-null   object
 18  title                 4803 non-null   object
 19  vote_average          4803 non-null   float64
 20  vote_count            4803 non-null   int64
 21  cast                  4760 non-null   object
 22  crew                  4803 non-null   object
 23  director              4773 non-null   object
dtypes: float64(3), int64(5), object(16)
memory usage: 900.7+ KB

In [8]:
df[:35]

    index  ...           director
0       0  ...      James Cameron
1       1  ...     Gore Verbinski
2       2  ...         Sam Mendes
3       3  ...  Christopher Nolan
4       4  ...     Andrew Stanton
5       5  ...          Sam Raimi
6       6  ...       Byron Howard
7       7  ...        Joss Whedon
8       8  ...        David Yates
9       9  ...        Zack Snyder
10     10  ...       Bryan Singer
11     11  ...       Marc Forster
12     12  ...     Gore Verbinski
13     13  ...     Gore Verbinski
14     14  ...        Zack Snyder
15     15  ...     Andrew Adamson
16     16  ...        Joss Whedon
17     17  ...       Rob Marshall
18     18  ...   Barry Sonnenfeld
19     19  ...      Peter Jackson
20     20  ...          Marc Webb
21     21  ...       Ridley Scott
22     22  ...      Peter Jackson
23     23  ...        Chris Weitz
24     24  ...      Peter Jackson
25     25  ...      James Cameron
26     26  ...      Anthony Russo
27     27  ...         Peter Berg
28     28  ...    Colin Trevorrow
29     29  ...         Sam Mendes
30     30  ...          Sam Raimi
31     31  ...        Shane Black
32     32  ...         Tim Burton
33     33  ...       Brett Ratner
34     34  ...        Dan Scanlon

[35 rows x 24 columns]

In [9]:
df.describe()

             index        budget  ...  vote_average    vote_count
count  4803.000000  4.803000e+03  ...   4803.000000   4803.000000
mean   2401.000000  2.904504e+07  ...      6.092172    690.217989
std    1386.651002  4.072239e+07  ...      1.194612   1234.585891
min       0.000000  0.000000e+00  ...      0.000000      0.000000
25%    1200.500000  7.900000e+05  ...      5.600000     54.000000
50%    2401.000000  1.500000e+07  ...      6.200000    235.000000
75%    3601.500000  4.000000e+07  ...      6.800000    737.000000
max    4802.000000  3.800000e+08  ...     10.000000  13752.000000

[8 rows x 8 columns]

In [10]:
df.columns

Index(['index', 'budget', 'genres', 'homepage', 'id', 'keywords',
       'original_language', 'original_title', 'overview', 'popularity',
       'production_companies', 'production_countries', 'release_date',
       'revenue', 'runtime', 'spoken_languages', 'status', 'tagline', 'title',
       'vote_average', 'vote_count', 'cast', 'crew', 'director'],
      dtype='object')

In [0]:
##Step 2: Select Features

features=['keywords','cast','genres','director']

In [12]:
##Step 3: Create a column in DF which combines all selected features

for features in features:
  df[features]=df[features].fillna('')
def combined_features(row):
  try:
      return row['keywords']+' '+row['cast']+' '+row['genres']+' '+row['director']
  except:
      print ('Error:',row)

df['combined_Features']=df.apply(combined_features,axis=1)

print ('Combined Features:',df["combined_Features"].head())

Combined Features: 0    culture clash future space war space colony so...
1    ocean drug abuse exotic island east india trad...
2    spy based on novel secret agent sequel mi6 Dan...
3    dc comics crime fighter terrorist secret ident...
4    based on novel mars medallion space travel pri...
Name: combined_Features, dtype: object

In [0]:
##Step 4: Create count matrix from this new combined column

cv1=CountVectorizer();
count_matrix1=cv1.fit_transform(df['combined_Features']);

In [0]:
##Step 5: Compute the Cosine Similarity based on the count_matrix

similarity_scores1=cosine_similarity(count_matrix1)

In [0]:
def get_index_from_title(title):
	return df[df.title == title]["index"].values[0]

In [0]:
movie_user_likes = "Avatar"

## Step 6: Get index of this movie from its title


movie_index= get_index_from_title(movie_user_likes)

In [0]:
## Step 7: Get a list of similar movies in descending order of similarity score


similar_movies=list(enumerate(similarity_scores1[movie_index]))
 
sorted_similar_movies=sorted(similar_movies,key=lambda x:x[1],reverse=True)

In [18]:
## Step 8: Print titles of first 50 movies

i=1
for movie in sorted_similar_movies:
  print (get_title_from_index(movie[0]))
  i+=1
  if(i>50):
    break

Avatar
Guardians of the Galaxy
Aliens
Star Wars: Clone Wars: Volume 1
Star Trek Into Darkness
Star Trek Beyond
Alien
Lockout
Jason X
The Helix... Loaded
Moonraker
Planet of the Apes
Galaxy Quest
Gravity
Alien³
Jupiter Ascending
The Wolverine
Silent Running
Zathura: A Space Adventure
Trekkies
Cargo
Wing Commander
Star Trek
Lost in Space
Babylon A.D.
The Fifth Element
Oblivion
Titan A.E.
AVP: Alien vs. Predator
The Empire Strikes Back
Dragonball Evolution
Superman Returns
Divergent
John Carter
The Black Hole
The Ice Pirates
Memoirs of an Invisible Man
Starship Troopers
The Astronaut's Wife
Machete Kills
Soldier
The Abyss
Damnation Alley
Men in Black
Space Cowboys
Space Dogs
The Time Machine
Sheena
Captain America: Civil War
Star Trek: Insurrection